name = "facebookdownbot" # ‡∂î‡∂∂‡∑ö Worker ‡∂±‡∂∏ ‡∂∏‡∑ô‡∑Ñ‡∑í ‡∂Ø‡∂∏‡∂±‡∑ä‡∂±.
main = "src/worker.js"
compatibility_date = "2024-11-01" # ‡∂∏‡∑ô‡∂∫ ‡∑Ä‡∂≠‡∑ä‡∂∏‡∂±‡∑ä ‡∂Ø‡∑í‡∂±‡∂ß ‡∑Ñ‡∑ù ‡∂ä‡∂ß ‡∂Ü‡∑É‡∂±‡∑ä‡∂± ‡∂Ø‡∑í‡∂±‡∂ö‡∂ß ‡∂∫‡∑ú‡∂Ø‡∂±‡∑ä‡∂±.
workers_dev = true

# =========================================================
# üí° ‡∑Ä‡∑í‡∑É‡∂≥‡∑î‡∂∏: ‡∂∏‡∑ô‡∂∏ ‡∂ö‡∑ú‡∂ß‡∑É ‡∂ë‡∂ö‡∑ä ‡∂ö‡∂ª‡∂±‡∑ä‡∂±.
# =========================================================
[build]
command = "npm run build" # ‡∑Ñ‡∑ù "bun run build"
watch_dir = "src"

[worker]
# ‡∂∏‡∑ô‡∂∏ workers ‡∂ö‡∑ú‡∂ß‡∑É ‡∂Ø‡∑ê‡∂±‡∂ß‡∂∏‡∂≠‡∑ä ‡∂≠‡∑í‡∂∂‡∑í‡∂∫ ‡∑Ñ‡∑ê‡∂ö.
# ‡∂∏‡∑ô‡∑Ñ‡∑í compatibility_flags ‡∂ë‡∂ö‡∑ä ‡∂ö‡∂ª‡∂±‡∑ä‡∂±.
compatibility_flags = ["nodejs_compat"]

# [durable_objects] ‡∑Ä‡∑ê‡∂±‡∑í ‡∑Ä‡∑ô‡∂±‡∂≠‡∑ä ‡∂ö‡∑ú‡∂ß‡∑É‡∑ä ‡∂≠‡∑í‡∂∂‡∑ö ‡∂±‡∂∏‡∑ä ‡∂í‡∑Ä‡∑è ‡∂ë‡∂Ω‡∑ô‡∑É‡∂∏ ‡∂≠‡∂∂‡∂±‡∑ä‡∂±.
[observability]
enabled = true
